// eslint-disable-file

const pasta = [
`
(╯°□°)╯︵ ┻━┻ FLIP THAT TABLE.
┻━┻ ︵ ヽ(°□°ヽ) FLIP THIS TABLE.
┻━┻ ︵ ＼\('0')/／ ︵ ┻━┻ FLIP ALL THE TABLES
ಠ_ಠ Son... ಠ_ಠ Put. ಠ__ಠ The tables. ಠ___ಠ Back.
(╮°-°)╮┳━┳ 
(╯°□°)╯︵ ┻━┻ NEVER!!!!
`,
`What was the most outstanding learning within the M60 community? The most remarkable learning within the community is certainly to respect the individuality of each one's process and how each member supports the other in the journey that, despite being walked alone, can have the help of several colleagues to support and encourage each other.`,
`im just looking for a butt that can cook and a streamer that can stream. is that too butt to butt? what a shame`,
`The Fart-a-Thon® is held to draw awareness to the disastrous disease known as colorectal cancer. A simple yearly screening is all it takes to hopefully catch and eradicate it before progression takes place. Adults reaching 45 are encouraged to get a camera shoved up their ass ASAP! Visit tip.m60.live to pay for more farts and call your doctor for more information.`,
`they’re still coming around. Reaction channels still talk about her every day. She’s almost iconic. And I think the mods are doing fine. This chat is much better than the first`,
`if you do get offended what Jake says you should not be in here Jake says what he wants to say if you don't like the way he's getting get back on the interstate and if you do get offended easily get the f*** out of the stream`,
`Wow, a cow made of butter. My girls would love it. In fact, the first sentence Caroline ever said was "I like butter"`,
`why are you sitting on the floor? why do you make the resting bitch face? why do you play music? why does your chat spam copypasta? why do you take toilet breaks on stream? what mic is that? why are you upset about the slow chat? why do you make fun of viewers for being stupid? why can't we be friends? why do you point your middle finger to the camera? why do you sing and dance on stream? why do you always have tech issues? why do you wear shorts? why do you misread chat messages?`,
`they’re still coming around. Reaction channels still talk about her every day. She’s almost iconic. And I think the mods are doing fine. This chat is much better than the first`,
`It’s me MrzParkerson 😂 y you so mad at me man 😂 where is the link it took 10 mins to comment 😂`,
`i come to you with my problems and in doing so i expect for you to agree with me, what part dont you understand`,
`lizzy you are going to meet me at my studrio and we are going to practive me and isabella were supposed to sing at this award shwo but we cant becuause she fled the country`,
`got kicked from the discord. but did you see 343 has announced no more EU or AU players with vpns connect to us servers cause that was the reason for desync. i was right about EU and AU players causing the game to crash`,
`@Twitch I'm having trouble purchasing bits`,
`Sorry to join chat to aplogize: But I wanted to say sorry about what happened with the discord link last night. My account got hacked. just wanted to say sorry again`,
`If you like the flavor of herb, I highly recommend looking into them. The Dynavap is the one I recommend to people starting in the vape world, its cheap and can work with flower and concentrates`,
`Ana did u hear about him scamming his community by not dying his hair blue? What else does he lie about`,
`everyones discussing bullies what about a community going after 2 people. what about a content creator going after people without voices n a group joining in? that's bullying.`,
`LUL`,
`@pepguy smells like @bootypatrol`,
`are you serious this started because death bullied an innocent woman in the server in front of everyone she should of taken it to DM's thats how it started why are you lying this is so upsetting`,
`i lost my job at k-mart cause we couldnt keep anything on the shelves so they shut down the k-mart`,
`Jamie Lynn ... congrats babe! You've stooped to a whole new level of LOW… please stop with these crazy lies for the Hollywood books !!! NOW and only NOW I do know only a scum person would make up such things about someone.`,
`I come in the room and what do I do? What do I do? I hit that follow button. I'm just here to check it out man. Not sure I want to sub yet OK. I sub to a guy with shorts like that people might start talking`,
`This channel is for entertainment purposes only and does not constitute medical diagnosis, advice or treatment. If you feel you are in need of care please seek services from a licensed professional. If this is a medical emergency please call 911 or the equivalent number in your country. No liability is accepted by Anavoir, Twitch or the community.`,
`I’m so happy that your subathon was during hasan’s ban. Really gave me the chance to watch you and enjoy you as a streamer ❤️ ❤️ ❤️`,
`Disappointed to see many of you tweeting about how Biden pooped his pants. It’s irresponsible to spread rumors like that. Stop posting about the poopy pants subject. Do not call more attention to the issue of Biden shitting himself. And no more hashtags like #PoopGate please!`,
`Contrary to popular belief the plural of shrimp is just shrimp`,
`Trump was intimated by her because she is a beautiful strong woman who isn't afraid to talk about the elephant in the room she pulls no punches and goes right to the truth no matter who it is`,
`Hi @m60_ I wanted to take a second to let you know that I find you very attractive. I've thought your profile picture was handsome for a long time and it's cool to see your Facebook wall and your Farmville farm. I wanted to see if there was any way I could get a poke back. I know it's a weird way to do this but I'm too scared of confrontation and it's easier to be let down like this if not. I have no intention of posting about it on my wall. I will even set pokes to private if I must.`,
`So the situation is, we have a vtuber discussing abuse with a unstable woman on Twitch while emoji's fly across the screen. How is this the timeline we are on?`,
`honestly ive been on an elimination diet and the one thing ive learned is my body just prefers double cheeseburgers from mcdonalds, we're all built differently`,
`Trump is the greatest president I’ve ever seen in my entire lifetime since 1993, Bush is a murderer, Obama is a piece of trash, Biden should be in a nursing home, fuck you chat`,
`Verbal assault is the same as physical assault, it’s just attacking a different part of the body`,
`Buts the fact she is a partner and spreading toxic behavior when she says she about positivity. Like be honest. Also decline the partnership program if you want to be toxic cuz you agree to being a positive role model.`,
`im very successful in worrying about myself. very great advocate for myself. very resilient and proficient`,
`I’m reporting you to do wheat`,
`@m60_ let me know what your partner manager has to see you big ok fucking cloen`,
`I’m reporting you to do wheat`,
`if i was going to a therapist i'd want one that has a "wine o clock" magnet on their mini fridge`,
`The thing is and i will tell it to you straight away. The world has alot of dark place and we will not be able to save it. Facts. Alot of terrible things happen in areas/country were a life doesnt matter alot. so what you wanna do? good luck fighting China, Russia, Iran. wont work, wont happen`,
`But if we don’t try then what the fuck is stopping us from just throwing ourselves off a bridge, and giving up, and saying “Yeah the planet is dying. The government hates us. The animals are leaving. The aliens aren’t contacting us. We might be alone. It just might be you and me.” But that’s okay. Because do you really need anyone else!?`,
`these ppl are so dumb. they have no idea what true dopamine rush is. they needa get some 99s in runescape`,
`Streaming while being a parent comes with interruptions from your family, them showing up on stream, sometimes you hear them in the background, more breaks than usual when you need to attend your kid(s), if your partner is working late or you are by yourself, they depend on you..`,
`Today is my one-year straightiversary. A year ago today, I put sodomy and lust behind me to live according to God’s wishes. In that time, I’ve only slipped up once, which, I’m told, is a big achievement for a first attempt.`,
`Change stream title to include #ad (for the sponsored segmant) and !Solitaire for the entire stream`,
`clint shoved his penis through the computer screen and made someone leave the internet`,
`I overdrawn my bank account to subscribe to @m60_ if I can, you can too!`,
`tanner take notes, this is what content looks like`,
`Oh, I messaged my partnership manager about it. I have already made it clear to him he cannot play my stream or any content from my stream on his stream. I've made it clear that I do not want him talking about me, and I don't talk about him... (unless its in regards to how he won't leave me alone and how his audience has been harassing me for months...) This is actually just harassment. I'm really curious to see how much he will twist things and I'm honestly expecting just a flat out lie.`,
`imagine being so insecure in your relationship that you need the government to give you a piece of a paper`,
`In South Korea, women are ridiculing men with the "pinching hand" emoji 🤏 to protest pay and labor inequalities. Men have built a reversal of the #MeToo movement to fight back.`,
`Here because of Dream? A user made a helpful infographic explaining the connection between Dream and the 2016 picture (where he is very fat).`,
`What fatphobia, who's scared of fat fucks, just walk quickly lol. Only my fridge is scared of fat fucks.`,
`hey any bitches who love my virtue signaling dm me nudes`,
`Idk, im not one to jump on justice wagon to mob someone with out knowing the full context. But watching these things is supper fucking cringe, if he did do it, let the man go to jail and be raped. Everyone on this stream is just there for there dopamine hit thinking there some social justice hero, funneling there hate and chicken tenddie energy saying pedo and groomer like gamers say "gamer words" even that fat chick at the top is smoking a cig(blunt?) like she just finished cumming`,
`I hope they include the 7+inch tag I've been emailing them about. I just can't relate to streamers under that cock length. They haven't been through the same struggle as me so I want to filter out anybody who isn't under that tag.`,
`Feels like you just want more female content creators posting nudes and you're trying to pass it off as supporting female content creators. It comes off as super scummy imo, considering many content creators are just hanging out and playing games with their community.`,
`I’m a straight white knight, no doubt about it. You got a problem, go seek elsewhere. Twitch is not for this content at all. The staff are going to ban her at some point, and none of you trolls can do a thing about it. This isn’t an adult site and it’s definitely something trolls who act like they’re 12 should be watching`,
`thoughts on karl jacobs? ok well ill take the bait, everyone trying to white wash that ice poseidon was a racist but its "okay" because he was popular has lost the point. nobody should have been watching that crap and the racism was on full display across twitch while he was still on the platform in 2016. glad to see that someone has outgrown racism but there's nothing wrong with taking accountability for your past choices.`,
`I kinda remember when mitch jones when pretty much friend with trainwrecks even some bullshit drama and whatever. Even he also friend byron he pretty much happy. But since him gone, hes kinda wonder why feel like sadness after this situation. But until now, mitch pretty much mature a lot and happy with him when he moving mizkif house to make something real life happy whatever he wanted even also they got some a lot Austin Streamer friend who live around here to cheer him up pursuit of happiness.As far I right now, He not said that 100% quit but he also want do new something stuff whatever music and they want. But he will appear him on stream whatever mizkif, maya and other around Austin streamer friend. I really kinda hope make him better happy after finally get more friend around with him`,
`all I'm asking for is a dollar okay I'm trying to ask for a dollar to take care of my home that's it`,
`I dont live in america noone here even wears mask i still work nothing has changed`,
`what did yall do with your $1400 stimulis crazy cant even fins a car for that now days lol i miss the 500 car 90s 2011 was the begining of the End`,
`We've been trying to reach you concerning your vehicle's extended warranty. You should've received a notice in the mail about your car's extended warranty eligibility. Since we've not gotten a response, we're giving you a final courtesy call before we close out your file. Press 2 to be removed and placed on our do-not-call list. To speak to someone about possibly extending or reinstating your vehicle's warranty, press 1 to speak with a warranty specialist.`,
`the I in IRS is for incel. It's unfair for the IRS to tax live streamers who receive donations. Taxation without representation.`,
`this is top teir content, imagine twitch not putting this on the front page. you're really losing the plot these days @twitch staff`,
`This is going to sound crazy, but someone posted that same paragraph just a minute ago.`,
`there's a mental health pandemic right now a lot of people are struggling mentally and it's very unfortunate. we need to be nicer to each other 😦`,
`Hold that Tot – your main spud, MR. POTATO HEAD isn’t going anywhere! While it was announced today that the POTATO HEAD brand name & logo are dropping the ‘MR.’ I yam proud to confirm that MR. & MRS. POTATO HEAD aren’t going anywhere and will remain MR. & MRS. POTATO HEAD`,
`There was no open wounds, there was no blood, there was no pee/poop AND I never peed or pooped in the pool, there was no vomit, there was no spit. @TwitchSupport I have spent the last 3 months turning my life around losing weight, quitting drinking, etc. And now this... ffs`,
`Good morning everyone!  Lot's of comments lately that I'm gonna die eating Dollar Tree foods.  For what it's worth I do NOT eat 98% of the foods you see in the processed foods videos.  I take a couple bites to do the video and that's it!  Every once in a while I will find something that isn't terribly unhealthy and delicious that I will eat.  Other than on those rare occasions the food is tossed after the taste test.`,
`TDS is "Trump Deragement Syndrome". Generally conservatives use it as a way to dismiss any and all criticism and or/justified rage at Trump. The irony is that in not acknowledging the horror that is Trump, they themselves are being deranged as it pertains to Trump, thus they are actually projecting, and have TDS.`,
`You’re such a back stabbing piece of shit. You were helping and a part of bobs manifesto and you knew exactly everything that happened in that call. I can’t believe you helped him with this even though you knew he 100% leaked your nudes. I’m so fucking done with you. I trusted you so hard and I really liked and cared about you. You’re such a horrible piece of shit. Hope you have a happy life being one of those fake fuck back stabbing streamer fucks. Disgusting cunt`,
`​can anyone tell me the name of the man that wears wigs? and talks about our gorl. I like to go give him a piece of my mind cuz no woman should be talked that way by a man. `,
`I actually went out to a winery two weeks ago and got a charcuterie board. They gave me salami, crackers, and cheddar cheese and charged me $60. I felt like I was eating an adult lunchable. Depression`,
`OH SHUT UP WITH THAT BS BEES KNEES SPACE AND TIME NONSENSE... THATS JUST THE COKE TALKING WITH YOUR ELEVATOR MUSIC.`,
`Praying this didn’t take alot. Music just isn’t for you sweetie. Don’t waste any more time on it`,
`Bro i forgot how annoying you are time to go lololol enjoy the free sub but losin the follow cy@ m60Salt m60Salt m60Salt m60Salt m60Salt m60Salt m60Salt m60Salt m60Salt m60Salt m60Salt`,
`HolidayTree ME TREE HolidayTree ME SPAM HolidayTree NO OXYGEN HolidayTree IF BAN HolidayTree`,
`Just to be clear, my daughter won't be sitting in some old dude's lap and telling him what a good girl she's been, so he can break into our house and give her presents while she sleeps.`,
`lost a follower here. if you went by your middle name, maybe people would care more Matt`,
`I love seeing TRUMP lose, it's my daily medicine, my weekly energy, my monthly inspiration and my yearly motivation. His loss is the only reason i'm still alive, i was born to love and enjoy the failure that he has achieved.`,
`Your content seems like someone pathetically desperate to be even the slightest bit relevant when you aren't in the slightest and will never be because you are a baby emotionally and not entertaining in the slightest when compared with other GTA streamers`,
`That looks NOT like balsamic vinaigrette at all! Vinaigrette is not thick, when you do it from basic ingredients it looks watery and is not thick. Everything looked very good until that thick "sauce" distroyed these fresh, good ingredients!! Don´t do your food the ALR way = distroying fresh, organic vegs and cheese and meat. All these sauces and fat cheese that ALR murders her food with is not necessary! They make you FAT!!! Please buy a cook book and read it before you distroy your food the ALR way. And you will feel better and you will lose weight, I promise....`,
`most people don't know, that dog food company's have to meet FDA standards for human consumption, incase of another depression.`,
`that boy that faked being trapped in a run away balloon like 10 years ago was probably the most iconic moment of our lifetime`,
`nikocado, my love. what a beguiling, breathtaking mukbanger you are. i love the sounds of your mouth as you chew your weekly 47th chicken nugget, along with the hysterical jokes you make which i find so, so appealing. once i get employed at a workplace, i shall invest in only buying your onlyfans. i am incredibly thrilled to see your mammoth-sized, juicy, voluptuous, tender, moist arsecheeks. i love you.`,
`My son got banned from @AlinityTwitch chat because he said something awful. I am so upset with him. I am trying to decide on the consequences. I am really sorry @AlinityTwitch, you don’t need that in your life.`,
`greekgodx is basic A NOBODY from britain 400 pounds who sniped loltyler1 in video games and after speaking to him over the mic for a few months he started streaming.. after 4 months with no face came and a huge tyler1 soddapopping following he started streaming facecam and lost 200 pounds and does irl and is super nice and is firends with mitch jones and trainwrecks, these are ices friends but he hates his firends , they all talk about andys everyday and scuffed`,
`the trolls keep trying to get me banned by getting me to say something that gets me banned. they fail i just put them on ignore. they are very entertaining with the ignorance`,
`Bits are not a currency. Bits are a fun, exciting new way for you to support your favorite streamers by cheering in the chat. `,
`Can you please put that finger away, its right in my face and is extremely phallic`,
`So to be a great president you have to give everybody covid-19 and give 80% of the country their job losses, and don't forget we didnt have any toilet paper`,
`Did anyone else realize that Amber Heard and Johnny Depp are just like amongus? Think about it: They met on a movie set (crewmates), Amber Heard lies about domestic abuse (sussy imposter), Amber Heard broke his phone while he was recording her (sabotaging comms). Amber Heard also dated Elon Musk, who went to space! And she got Johnny Depp Ejected from his house, just like in Amongus. The whole Amber Heard Johnny Depp thing is basically Amongus! Incredible, I never realized it until now!`,
`#BelieveAllWomen`,
`ImTyping`,
`Hi m60_ - It’s me, your only Viewer. For Months I have created the illusion that you are streaming to a large audience. But here’s the truth: all these people in the chat are me. And now, for you to be convinced of this, I will send this message from all my accounts. m60P`,
]

export default pasta;
